Fixes #2 : Provisional Board Management UI
Lyearn/szachy pull request #3
Opened 2020-10-25 17:08 UTC by Smit2010

@statebait Please review and suggest changes

2020-10-28 20:39 UTC, statebait requested changes
Some changes to be done:

Avoid using inline styling. Use emotion for styling. eg:

Create a file called styles.ts for a specific component:

```jsx
import { css } from "emotion";

export const someStyle = css`
    color: red;
`
```

In your component:

```jsx
import { someStyle } from "./styles.ts";
....
<Component className={someStyle}>
....
</Component>
```

Make sure to change this everywhere.

Please remove the package-lock.json. We are using yarn as our package manager.

2020-10-28 20:39 UTC, statebait commented on src/components/dashboard/Dashboard.tsx
> +import React, { useState } from "react";
Rename this to index.tsx so the imports will be /components/dashboard

Breakdown this component into smaller components.

2020-10-28 20:39 UTC, statebait commented on src/components/dashboard/components/OpenGames.tsx
> +import React from "react";
Breakdown the component into smaller components.

2020-10-28 20:39 UTC, statebait commented on src/components/dashboard/components/NewGameDialog.tsx
> +import React, { useState } from "react";
Breakdown this component.

2020-11-03 19:41 UTC, Smit2010 commented
@statebait Please review and suggest any changes if any. Thanks.

2020-11-07 16:38 UTC, statebait approved these changes
LGTM!

2020-11-10 08:11 UTC, merged

2020-11-10 08:13 UTC, statebait commented
give @Smit2010 150 points